### PR TITLE
Fixed the lightbulb examples

### PR DESCRIPTION
**Pull request by ghost**
Sorry for breaking them, I should have tested everything first 😖

mypy and flake8 both passed, but if there's any changes you'd like me to make I can :)

### CODE REVIEW

**Comment by vicky5124** [comment]
First, this cannot be merged without the merge conflicts being resolved.
And to make sure this example is made to work, for it to be merged I would like for CI to be updated, so this example gets tested with `mypy --strict`

**Comment by ghost** [comment]
I'll fix the conflicts later today when I'm home, and make sure mypy passes :)

**Comment by ghost** [comment]
I've resolved the merge conflicts, I hope everything's okay to merge now

**Review by vicky5124 — CHANGES_REQUESTED** [review]
`.github/ci.yml` should be updated to check for `mypy --strict` in this example.

**Comment by Jonxslays** [comment]
I was taking a look at the CI, is it really necessary to run tools like black, and flake8 on multiple different OS's? Couldn't you restrict them to just ubuntu-latest for example?

**Comment by vicky5124** [comment]
> I was taking a look at the CI, is it really necessary to run tools like black, and flake8 on multiple different OS's? Couldn't you restrict them to just ubuntu-latest for example?

Maybe not black, but I have seen flake8 vary depending on the OS. Black  takes just milliseconds to run, so I don't really mind.

**Comment by Jonxslays** [comment]
Interesting, that makes sense.

**Review by ghost — COMMENTED** [review]
Updated the ci in [this commit](https://github.com/vicky5124/lavasnek_rs/pull/20/commits/516a995c8c8434f24e3da6c07c2bf370cb1a9be2), hope it's right as I've never done that before 😅

**Review by vicky5124 — APPROVED** [review]

**Pull request merged**
